const demoReplyTemplates = [
  "Thank you for staying with us and for sharing your experience. We are glad the visit felt smooth, and we would be happy to host you again.",
  "We appreciate your thoughtful review. Your feedback helps our team keep improving the stay experience for future guests.",
  "Thank you for choosing our property. We are pleased to hear what worked well during your stay and will keep using your feedback to make each visit better.",
  "Thank you for the kind review. It means a lot to know the space supported your trip, and we hope to welcome you back soon.",
  "We are grateful for your feedback and for taking the time to write a review. Our team will keep focusing on the details that make each stay comfortable.",
  "Thank you for your review. We are happy the stay met your expectations and appreciate you highlighting the parts that made your trip easier.",
  "We are so pleased to hear you enjoyed your time with us. Thank you for sharing your impressions, and we would be glad to host you again.",
  "Thank you for the generous feedback. Our team works hard to keep every stay comfortable, and your comments are very encouraging.",
  "We appreciate you taking the time to review your stay. It is wonderful to know the property supported a relaxing visit.",
  "Thank you for being our guest. We are glad you had a positive stay and appreciate the details you shared in your review.",
  "Your feedback is greatly appreciated. We are happy to hear the stay went well and will continue working to make each visit even better.",
  "Thank you for the thoughtful note. We are pleased the experience was a good fit for your trip and hope to welcome you again soon.",
  "We appreciate your kind words. It is always rewarding to hear when guests feel comfortable and well supported during their stay.",
  "Thank you for staying with us. We are glad the property helped make your trip more convenient and enjoyable.",
  "We are grateful for your review and for choosing our place. Your comments mean a lot to our team.",
  "Thank you for sharing this feedback. We are happy to know you enjoyed the stay and appreciate you pointing out what worked well.",
  "We appreciate your review. Our team will keep building on the details that helped make your visit a good one.",
  "Thank you for taking the time to write about your stay. We are glad you had a comfortable experience with us.",
  "We are pleased to hear your stay went smoothly. Thank you for being our guest and for leaving such helpful feedback.",
  "Thank you for the warm review. It is great to know the property matched your needs during the trip.",
  "We appreciate your feedback and are glad the stay left a positive impression. We hope to host you again in the future.",
  "Thank you for your kind comments. We are happy the visit was comfortable and will keep working to deliver that same standard.",
  "We are glad you enjoyed your stay. Thank you for sharing your experience and for choosing our property.",
  "Thank you for the review. Your feedback helps us understand what guests value most and where we can keep improving.",
  "We appreciate the time you took to leave feedback. We are pleased to hear the stay was a positive part of your trip.",
  "Thank you for staying with us. We are happy the experience was smooth and appreciate your thoughtful review.",
  "We are grateful for your comments. It is good to know the property worked well for your plans.",
  "Thank you for choosing us for your trip. We appreciate your review and are glad the stay was comfortable.",
  "We appreciate your feedback. Our team is pleased to hear the visit went well and that you enjoyed your time at the property.",
  "Thank you for your review. We are glad you noticed the care our team puts into preparing each stay.",
  "We are happy to hear you had a good experience. Thank you for the kind words and for staying with us.",
  "Thank you for sharing your thoughts. We appreciate your feedback and will continue using it to improve the guest experience.",
  "We are pleased the stay suited your needs. Thank you for taking the time to leave a helpful review.",
  "Thank you for the positive feedback. We are glad your visit was easy and comfortable from start to finish.",
  "We appreciate you choosing our property. Thank you for the review, and we hope your trip was a memorable one.",
  "Thank you for your thoughtful comments. We are happy to hear that the stay supported your plans so well.",
  "We are grateful you took the time to share your experience. Your feedback is encouraging and genuinely useful to our team.",
  "Thank you for the kind review. We are glad the property provided a comfortable base for your visit.",
  "We appreciate your note and are pleased the stay went smoothly. It would be a pleasure to host you again.",
  "Thank you for your feedback. We are glad you enjoyed the space and appreciate you letting us know about your stay.",
  "We are happy to hear the stay was a good experience. Thank you for choosing us and for sharing your review.",
  "Thank you for staying at our property. We value your feedback and are glad the visit was enjoyable.",
  "We appreciate your review and the care you took in sharing your thoughts. Our team will keep using feedback like this to improve.",
  "Thank you for the lovely feedback. We are pleased the details of the stay helped make your trip more comfortable.",
  "We are glad you had a positive stay with us. Thank you for taking the time to leave such a helpful review.",
  "Thank you for sharing your experience. We appreciate your comments and are happy the property worked well for your trip.",
  "We are grateful for your review. It is encouraging to know the stay met your needs, and we hope to welcome you back.",
  "Thank you for choosing our place. We appreciate your feedback and are glad the stay was a comfortable one.",
  "We appreciate your comments and are happy the stay was a good fit. Thank you for trusting us with your trip.",
  "Thank you for staying with us and for leaving a review. We are glad your experience was positive and hope to host you again.",
];

export function generateDemoReviewReply() {
  return demoReplyTemplates[
    Math.floor(Math.random() * demoReplyTemplates.length)
  ];
}
